services:
  - type: web
    name: resona-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd ../.. && npm install --ignore-scripts && cd packages/backend && npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: resona-db
          property: connectionString
